on:
  pull_request:
    branches:
      - master
name: PR Workflow
jobs:
  validate_configurations:
    name: Validate JSON Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Permissions
        uses: coderbydesign/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schemas/permissions.schema
          json_path_pattern: ./configs/permissions/*.json$
          send_comment: true
      - name: Validate Roles
        uses: coderbydesign/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schemas/roles.schema
          json_path_pattern: ./configs/roles/*.json$
          send_comment: true
          
