on:
  pull_request:
    branches:
      - master
name: PR Workflow
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Permissions Against Schema
        uses: walbo/validate-json@v1.1.0
        with:
          files: ./configs/.*/permissions/.*json
          schema: ./schemas/permissions.schema
      - name: Validate Roles Against Schema
        uses: walbo/validate-json@v1.1.0
        with:
          files: ./configs/.*/roles/.*json
          schema: ./schemas/roles.schema
