on:
  pull_request:
    branches:
      - master
name: PR Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    - name: Validate JSON files
      env:
        REPORT_ONLY: true
        SHOW_ERRORS: true
      run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
